name: CI

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'
      - name: Build the project
        run: ./gradlew build
